### PR TITLE
Adds gulp security task

### PR DESCRIPTION
**Pull request by jfmercer**
Adds gulp security task
--

### Description

* Installs `gulp-nsp`
* Creates gulp security task
* Adds security task to gulp default task
* Edits `CHANGELOG`

### Test Script

* **Assert that** Travis passes

### CODE REVIEW

**Comment by gavD** [comment]
please rebase this @jfmercer 

What does the gulp security task do? I'm assuming it verifies that none of the deps have known issues, yeah?

**Comment by jfmercer** [comment]
Right. It looks at package.json & confirms that none of the packages have
known security issues. It doesn't look at anything else in the repo. Just
package.json deps.

On Saturday, November 21, 2015, Gavin Davies <notifications@github.com>
wrote:

> please rebase this @jfmercer <https://github.com/jfmercer>
>
> What does the gulp security task do? I'm assuming it verifies that none of
> the deps have known issues, yeah?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radify/radiian/pull/53#issuecomment-158642040>.
>


-- 
John Mercer | Software Developer; Radify, Inc. | 1-949-606-5003

**Comment by gavD** [comment]
cool. Please rebase this and then happy to merge

**Comment by jfmercer** [comment]
I'm moving today. Might not rebase till Sunday or Monday. But I'll get to
it.

On Saturday, November 21, 2015, Gavin Davies <notifications@github.com>
wrote:

> cool. Please rebase this and then happy to merge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radify/radiian/pull/53#issuecomment-158643098>.
>


-- 
John Mercer | Software Developer; Radify, Inc. | 1-949-606-5003

**Comment by gavD** [comment]
there's no rush

**Comment by jfmercer** [comment]
@gavD Rebase complete. :+1:

**Pull request merged**
